export const GET_MOVIES_STARTED = "GET_MOVIES_STARTED";
export const GET_MOVIES_SUCCESS = "GET_MOVIES_SUCCESS";
export const GET_MOVIES_FAIL = "GET_MOVIES_FAIL";

export const GET_TRENDING_STARTED = "GET_TRENDING_STARTED";
export const GET_TRENDING_SUCCESS = "GET_TRENDING_SUCCESS";
export const GET_TRENDING_FAIL = "GET_TRENDING_FAIL";

export const GET_TOP_RATED_STARTED = "GET_TOP_RATED_STARTED";
export const GET_TOP_RATED_SUCCESS = "GET_TOP_RATED_SUCCESS";
export const GET_TOP_RATED_FAIL = "GET_TOP_RATED_FAIL";

export const GET_MOVIE_STARTED = "GET_MOVIE_STARTED";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_FAIL = "GET_MOVIE_FAIL";

export const SEARCH_STARTED = "SEARCH_STARTED";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAIL = "SEARCH_FAIL";

export const INPUT_SEARCH = "INPUT_SEARCH";
